version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: strapi_prova_senai
    env_file:
      - .env
    environment:
      POSTGRES_DB:   ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
